#:schema node_modules/wrangler/config-schema.json
name = "sublink-workers"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "e8da973caedf49bba9f17404b5e1a677" }
]

[assets]
directory = "./public"
